language: generic
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry git clone https://github.com/luckytyphlosion/agbcc.git -b new_layout_with_libs
  - cd agbcc && make && make install prefix=$TRAVIS_BUILD_DIR
  - popd
matrix:
  include:
    - os: linux
      env: _="Build"
      script:
        - ./build_tools.sh
        - make -j2
